;PROG TO SEPARATE ARRAY OF TEN NUMBERS INTO EVEN AND ODD
	AREA ARRAY,CODE,READONLY
	ENTRY
START
	MOV R6,#0
	LDR R0,=ARR
	LDR R1,=EVEN
	LDR R2,=ODD
LOOP	
	LDR R3,[R0],#4
	MOVS R4,R3,LSR#1
	STRCS R4,[R2],#4 	
	STRCC R4,[R1],#4
    ADD R6,#1
	CMP R6,#10
	BNE LOOP
HERE B HERE
ARR DCD 1,2,3,4,5,6,7,8,9,0XA
	AREA DATA1,DATA,READWRITE
EVEN DCD 0X0
ODD DCD 0X0
		END