;PROGRAM TO COUNT NO OF ONES IN A WORD
	AREA ONES,CODE,READONLY
	ENTRY
START
	LDR R0,COUNT;LENGTH OF WORD
	LDR R1,=0X0;NO OF ONES
	LDR R2,=NUM
	LDR R3,[R1]
	
NEXT
	LDR R3,R3,RRX
	ADDCS R1,R1,#1
	SUBS R0,R0,#1
	BNE NEXT
HERE B HERE
COUNT DCD 0X32
NUM DCD 0X12345678
	END