	;ALP to store a byte, a Half-word and a word in registers into memory locations
	AREA PROG_2,CODE,READONLY
	ENTRY
START
	MOV R4,#0X55
	LDR R5,=0X5678
	LDR R6,=0X22334455
	LDR R0,=BYTE
	LDR R1,=HALF
	LDR R2,=WORD
	STRB R4, [R0]
	STRH R5, [R1]
	STR R6, [R2]
HERE B HERE
	AREA LARGE_DATA, DATA, READWRITE
BYTE SPACE 1
	ALIGN 2
HALF SPACE 2
	ALIGN 4
WORD SPACE 4
	END
